# Las bases de Numpy

Toda la libreria de Numpy se articula alrededor de una unica estructura de datos: la matriz multidimensional o ndarray  (N-DIMENSIONAL Array)



CARACTERISTICAS BASICAS ndARRAY

* Una ndarray puede contener elementos de CUALQUIER TIPO
* Tods los elementos de una ndarray deden tener el mismo TIPO
* El tamaño de una ndarray (numero de elementos) se define en el momento de la creacion y no puede modificarse
* Pero la organizacion de esos elementos entre diferentes dimensiones si puede modificarse. (Cambiar el numero de columnas y filas)

USO BASICO DE CUALQUIER ELEMENTO DE NUMPY

Hay que recordar que Numpy no es un modulo del core de PyTHON por lo que siempre hay que importarlo de forma completa o complemento a complemento.


In [ ]:
import numpy as np #cada que se quiera utilizar una funcion de Numpy, poner el prefijo np.

### CREACION BASICA DE N.D.ARRAYS

Existen varias formas de crear un ndarrays en Numpy. Veamos lo basico;

In [ ]:
# CREACION DE UN NDARRAY VACIO (utilizar la funcion empty)
array_vacio = np.empty((3, 2), dtype=np.unicode) #especificando dimensiones, y el tipo de datos
array_vacio

In [ ]:
#Copiando dimensiones y tipo desde otra estructura
array_vacio_copia = np.empty_like([1, 2, 3, 4, 5]) #especificando dimensiones
array_vacio_copia # # es para cuando no conocemos la dimesnion 

In [ ]:
# CREACION DE UN NDARRAY DE UNOS
array_unos = np.ones((3, 2)) #especificando dimensiones
array_unos

In [ ]:
#Copiando dimensiones y tipo desde otra estructura
array_unos_copia = np.ones_like([1, 2, 3, 4, 5]) #especificando la estructura que queremos copiar, en este caso una lista,
array_unos_copia  # es para cuando no conocemos la dimesnion

In [ ]:
# CREACION DE UN NDARRAY DE CEROS
array_ceros = np.zeros((3, 2)) #especificando dimensiones
array_ceros

In [ ]:
#Copiando dimensiones y tipo desde otra estructura
array_ceros_copia = np.zeros_like([1, 2, 3, 4, 5]) #especificando dimensiones
array_ceros_copia  # es para cuando no conocemos la dimesnion 

In [ ]:
# CREACIONDE DE UNA MATRIZ IDENTIDAD
array_identidad = np.identity(3) #especificando dimensiones
array_identidad

In [ ]:
# CREACIONDE DE UNA ndarray CON UNOS EN UNA DE LAS DIAGONALES

#la iderancia con la identidas es que podemos mover la diagonal

#Cuadrada con unos en la diagonal principal
array_identidad = np.eye(4) #especificando dimensiones
array_identidad 

In [ ]:
#Cuadrada con unos en la diagonal especifica
array_identidad_dos = np.eye(4, k=1) #especificando dimensiones
array_identidad_dos

In [ ]:
#No cuadrada con unos en la diagonal en especifico
array_secuencia = np.eye(4, 3, k=-1) #especificando dimensiones
array_secuencia

In [ ]:
# CREACIONDE DE UNA ndarray CUYOS ELEMENTOS SON UNA SECUENCIA NUMERICA
array_secuencia1 = np.arange(10) #especificando el rango de los numeros
array_secuencia1 #lo arroja en una sola dimension

In [ ]:
array_secuencia2 = np.arange(5, 20, 2) #especificando dimensiones
array_secuencia2 #lo arroja en una sola dimension

In [ ]:
array_secuencia3 = np.arange(5, 10) #especificando dimensiones
array_secuencia3

In [ ]:
# CREACIONDE DE UNA ndarray A PARTIR DE UNA SECUENCAI BASICA DE PYTHON
#unidimesnional
array_basica = np.array([1, 2, 3, 4]) 
array_basica #nos arroja el tipo de elementos y los elementos

In [ ]:
#Multidimensional
array_multidimensional = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) # tienen que tener el mismo numero de elementos
array_multidimensional #en este caso nos lo arroja en dos dimesniones

### TIPOS DE N.D.ARRAYS DE NUMPY

* Enteros con signos: np.int8, np.int16, np.int32, np.int64
* Eneteros sin signo: np.uint8, np.uint16, np.uint32, np.uint64 CERO O POSITIVOS
* Numeros en comas flotantes: np.float16, np.float32, np.float64, np.float128
* Boleanos: np.bool
* Objetos: np.object (NONE O NA)
* Cadenas de Texto: np.string, np.unicode

ESPECIFICACION / CASTING / CONVERSION DE TIPO ENTRE N.D.ARRAYS

dntype nos ayuda a especificar el tipo de datos que queremos manejar, de acuardo a la lista anterio

In [ ]:
#ENTEROS
array_incial_enteros = np.array([1, 2, 3, 4, 5], dtype=np.int32)
array_incial_enteros

In [ ]:
#DECIMAL
array_incial_float = np.array([1, 2, 3, 4, 5], dtype=np.float64)
array_incial_float

In [ ]:
# TEXTO
array_incial_string = np.array([1, 2, 3, 4, 5], dtype=np.unicode_)
array_incial_string

### CONSULATA DE LA COMPOSICION DE UNA N.D.ARRAY

* dtype: tipo del contenido
* ndim: numero de dimensiones (Numero de filas y columnas)
* shape: estructura/forma de ndarray, numero de elementos en cada uno de los ejes/dimensiones (elementos de cada fila o columna) Forma
* size: numero total de elementos en el nd arrays (el tamaño no se puede cambiar)



In [ ]:
#Multidimensional
array_ = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) 
array_

In [ ]:
#TIPO DE ARRAY
array_.dtype

dtype('int64')

In [ ]:
# NUMERO DE DIMENSIONES
array_.ndim # se puede establecer por el numero de corchetes que hay en la funcion

In [ ]:
#FORMA/DIMESION
array_.shape

In [ ]:
#NUMERO TOTAL DE ELEMENTOS
array_.size

### OPERACIONES ARITMETICAS ENTRE N.D.ARRAYS Y ESCALARES

In [ ]:
#UN ARRAY CON UN NUMERO
array_op = np.array([1, 2, 3, 4], dtype=np.float64) 
array_op

In [ ]:
#SUMA
array_op + 5 # A cada elemento  le SUMA un valor

In [ ]:
#RESTA
array_op - 3 # A cada elemento  le RESTA un valor

In [ ]:
#MULTIPLICACION
array_op * 3 # A cada elemento  le MULT un valor

In [ ]:
#DIVISON
1 / array_op  # A cada elemento  le DIVIDE un valor

In [ ]:
#DIVISION ENTERA
array_op // 2 # A cada elemento  le DIV ENTERA un valor

In [ ]:
#POETENCIA
array_op ** 2 # A cada elemento  le POTENCIA un valor

In [ ]:
#ASIGNACION CON OPERADOR
array_op += 1
array_op

### OPERACIONES ARITMETICAS ENTRE N.D ARRAYS

IMPORTANTE: LOS DOS TERMINOS DE LAS OPERACIONES TIENEN QUE SER N.D.ARRAYS DE LAS MISMAS DIMENSIONES Y FORMA. SE APLICA LA OPERACION ELEMENTO A ELEMWNTO

In [ ]:
array_arr = np.array([1, 2, 3, 4], dtype=np.float64) 

In [ ]:
# SUMA
array_arr + array_arr

In [ ]:
# RESTA
array_arr - array_arr

In [ ]:
# MULTIPLICACION
array_arr * array_arr

In [ ]:
# DIVISION
array_arr / array_arr

In [ ]:
# ASIGNACION CON OPERADOR
array_arr += array_arr
array_arr

In [ ]:
#SUMA DE N.D.ARRAYS DE DIFERENTE DIMENSION
array_1 = np.array([1, 2, 3, 4, 5])
array_arr + array_1 #TIENEN QUE SER DE LAS MISMAS DIMENSIONES, YA QUE FUNCIONA ELEMENTO A ELEMENTO

### INDEXACION Y SLICING BASICO

En N.D.ARRAYS unidimensionales el funcionamiento es identico al que se tiene en secuencias basicas de Python. Es decir, se utiliza la indexacion [a:b:c]

In [ ]:
# RECUPERAR O IDENTIFICAR ELEMENTOS DE MI ARRAY
array_I = np.arange(1, 11)
array_I

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# INDEXACION CON PRIMER PARAMETRO
array_I[2] #localizar un elemento en especifica cuando se conoce la posicion

In [ ]:
# INDEXACION CON PRIMER PARAMETRO Y SEGUNDO PARAMETRO
array_I[2:5] #localizar un rango en especifica cuando se conoce las posiciones

In [ ]:
# INDEXACION CON TERCER PARAMETRO
array_I[::2] #localizar elementos en especifica con un orden especifico

In [ ]:
# INDEXACION CON NEGATIVOS
array_I[::-1] #replicar los elementos pero con un orden diferente, en este caso inveros

EN N.D.ARRAYS MULTIDIMESNIONALES EXISTEN DOS POSIBLES FORMAS DE REALIZAR EL ACCESO

* Mediante indexacion discursiva: array [a:b:c en dim_1][a:b:c en dim_2] ... [a:b:c en dim_n]
* Mediante indexacion con comas: [a:b:c en dim_1, a:b:c en dim_2, ... a:b:c en dim_n]

In [ ]:
array_UNO = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]]) 
array_UNO

In [ ]:
# FORMA DE LA MATRIZ
array_UNO.shape # para este caso son dos matrices externas con dos matrices internas y cuatro elementos para cada una

In [ ]:
# INDEXACION RECURSIVA PRIMER NIVEL
array_UNO[1] # nos arroja la segunda matriz externa

In [ ]:
# INDEXACION RECURSIVA SEGUNDO NIVEL
array_UNO[1][0] # Nos arroja la primer matriz interna de la segunda matriz externa

In [ ]:
# INDEXACION RECURSIVA TERCER NIVEL
array_UNO[1][0][3] # Nos arrojas el cuarto elemento de la primer matriz interna en la segunda matriz externa

In [ ]:
# INDEXACION CON COSAS SEGUNDO NIVEL
array_UNO[1, 0] # es lo mismo a lo anterior pero en lugar de corchetes son comas

In [ ]:
# INDEXACION CON COSAS TERCER NIVEL
array_UNO[1, 0, 3]

In [ ]:
# INDEXACION RECURSIVA TERCER NIVEL CON SLICE
array_UNO[0][0][:2] #Tambien se pueden seleccionar rangos

In [ ]:
# INDEXACION RECURSIVA TERCER NIVEL CON SLICE DE INDICE NEGATIVO
array_UNO[1][0][::-1] # y se puede cambiar el orden de los elementos

Del mismo modo a como ocurre en Python baisco, se puede utilizar la indexacion/ slicing para modificar secciones del contenido de  N.D.ARRAY

In [ ]:
array_UNO = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) 

In [ ]:
#MODIFICACION DE UNA POSICION
array_UNO[0][1] = 50
array_UNO #Podemos cambiar el valor de algun elemento, pero no podemos agregar elementos

In [ ]:
#MODIFICACION DE UN SLICE
array_UNO[0][::2] = 30
array_UNO # se puede aplicar un valor para un rango en especifico

### INDEXACION Y SLICING BOLEANO 

In [ ]:
personas = np.array(["Miguel", "Juan", "Pedro", "Luis"])
personas 

In [ ]:
datos = np.random.rand(4, 4)
datos

array([[0.34179357, 0.87408922, 0.88819279, 0.55695457],
       [0.95684061, 0.46559094, 0.63174406, 0.07634536],
       [0.35318061, 0.98290098, 0.63388924, 0.41298349],
       [0.92339578, 0.56555527, 0.46801138, 0.90064968]])

In [ ]:
# INDEXACION/SLICING BOLENAO SOBRE VALORES
datos < 0.5 # todos los valores menores a 0.5
datos[datos < 0.5] # Con esta funciones nos arroja el valor que cumplen la condicion de los corchetes

In [ ]:
# MASCARA BOLEANA
personas == "Miguel" #lo podemos aplicar para str

array([ True, False, False, False])

In [ ]:
# INDEXACION/SLICING MEDIANTE MASCARA 
datos[personas == "Miguel"] # No tiene que ser con la misma matriz en este caso nos arrojasla primer fila

# por que en en el aaray de personas solo la primera es "Miguel"

In [ ]:
# INDEXACION/SLICING MEDIANTE MASCARA Y BASICO COMBINADO
datos[personas == "Miguel", ::2] #Podemos indexar de igual forma

In [ ]:
# INDEXACION/SLICING MEDIANTE MASCARA NEGATIVO POR OPERADOR
datos[personas != "Miguel"] # He invertir nuestra seleccion para los elementos que no cumplan con esa condicion

In [ ]:
# INDEXACION/SLICING MEDIANTE MASCARA NEGATIVO POR SIGNO
datos[~(personas == "Miguel")] #para cambiar el signo de los valores utilizamos el simbolo ~

De nuevo, podemos utilizar indexacion/slicing boleano para realizar modificaciones sobre el contenido de un N.D.ARRAYS

In [ ]:
array_ = np.random.rand(7, 4)
array_

In [ ]:
# ELIMINACIONDE VALORES NEGATIVOS MEDIANTE EL SLICING
array_[array_ < 0.5] = 0 #Sustitutye todos lo valores que cumplen con la condicion por un valor asignado
array_ 

### INDEXACION Y SLICING BASADO EN SECUENCIAS DE ENTEROS (FANCY INDEXING)

In [ ]:
array2 = np.empty((8, 4))
for i in range(8):
  array2[i] = i
array2

In [ ]:
array2[[2, 5]] #Cuando queremos seleccionar elementos que no son consecutivos o del mismo rango
#Utilizamos dobles llaves para seleccioanrlos

In [ ]:
array2[[-2, -5]] # al igual que con cualquier indexacion podemos seleccionar de manera inversa

Tambien podemos indexar de manera arbitraria en multiples dimensiones, utilizando para ellos, una secuencia de enteros en cada dimension. El resultado sera la combinacion de secuencias; 

In [ ]:
array3 = np.arange(32).reshape((8, 4)) #podemos ajustar la fomra de la matriz con la funcion .reshape
array3

In [ ]:
array3 = np.array([[2, 5, 9, 1], [3, 6, 8, 9]]) 
array3

In [ ]:
array3 = np.array([[2, 5, 9, 1], [3, 6, 8, 9]]) 
array3

### TRASPOSICION Y MODIFICACION DE EJES/DIMESNSIONES

In [ ]:
array_t = np.arange(15)
array_t

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# MODIFICACION DE EJES/DIMENSIONES
array_t2 = array_t.reshape(3, 5)
array_t2

In [ ]:
# TRASPOSICION DE EJES/DIMENSIONES
array_t2.T

### CONCATENACION DE N.D.ARRAYS

Numpy ofrece la posibilidad de conbinar ndarrays de dos formas posibles:
* hstack,column_stack: los elementos del segundo array, se añaden a los del primero a lo ancho.**texto en negrita**
* vstack, row_stack: los elemenetos del segundo array se añaden a los de primero a lo largo 

In [ ]:
array_k = np.arange(15).reshape(3, 5)
array_k

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
array_k2 = np.arange(15, 30).reshape(3, 5)
array_k2

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
# CONCATENACION HORIZONTAL 
np.hstack((array_k, array_k2)) #UNIR POR COLUMNAS, DEBE TENER EL MISMO NUMERO DE  FILAS

array([[ 0,  1,  2,  3,  4, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14, 25, 26, 27, 28, 29]])

In [ ]:
# CONCATENACION VERTICAL 
np.vstack((array_k, array_k2))  #UNIR POR FILAS, DEBE TENER EL MISMO NUMERO DE  COLUMNAS

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### DIVISION DE N.D.ARRAYS 

Al igual que para la concatenacion, Numpy permite dividir los n.d.arrays de tres formas distintas:
* hsplit: division de arrays en "n" partes "iguales" por columnas
* vsplit: division de arrays en "n" partes "iguales" por filas
* split: division de arrays en "n" partes no simetricas


In [ ]:
array_C = np.arange(16).reshape(4, 4)
array_C #El punto es generar nuevos columnas o filas de la matirz original

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# DIVISION SIMETRICA POR COLUMNAS
np.hsplit(array_C, 2) #AGREGAR FILAS

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
# DIVISION SIMETRICA POR FILAS
np.vsplit(array_C, 2) #AGREGAR COLUMNAS

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
# DIVISION NO SIMETRICA 
np.split(array_C, [1, 3], axis=1) # SPLIT SE UTILIZA EJES

AXIS

* Valor 0: Aplica la funcion por columnas
* Valor 1: Aplica la funcion por filas