# OPERACIONES SOBRE N.D.ARRAYS

Numpy pone anuestra disposicion un amplio conjunto de funciones optimizadas para palicar sobre ndarrays de forma global evitando asi la necesidad de utilizar bucles (muchos mas costosos) 

In [ ]:
import  numpy as np

### OPERACIONES ELEMENTO A ELEMENTO (UNIVERSAL FUNCTIONS)

El primero de los conjuntos de funciones ofrecidos por Numpy son las llamadas "funciones universales" (o ufuncs) que permiten la realizacion de operaciones elemento a elemento de un array. En funcion del numero de parametros encontramos dos tipos de funciones universales:

FUNCIONES UNITARIAS 

Son aquellas funciones que reciben como parametros un unico ndarray
* abs, fabs : valor absoluto
* sqrt: raiz cuadrada ( equivalente a array *\*\ 0.5)
* square: potencia al cuadrado ( equivalente a array ** 2)
* exp: potencia de e
* log, log10, log2, log1p: logaritmos en distintos bases
* sign: signo (
* Ceil: techo (Redondear hacia arrriba)
* floor: suelo  (Redondear hacia abajo)
* Rint: redondeo al entero mas cercano
* modf: devuelve dos arrays una con la parte fraccionaria fracciones y otra con enteros
* inan: devuelve un array boleano indicando si el valor es finito o infinito
* isfinite, isinf: devuelve un array boleano indicando si el valor es finito o infinito
* cos, cosh, sin, sinh, tan, tanh: funciones trigonometricas
* arcco, arccosh, arcsin, arcsinh, arctan, arctanh: funciones trigonometricas inversas
* logical_not: inverso boleano de todos los valores del array

In [ ]:
array = np.array([-1, 2, 3, 4, 5]) #valores absolutos
np.abs(array)

array([1, 2, 3, 4, 5])

In [ ]:
np.sign(array) # signo negativo o positivo

array([-1,  1,  1,  1,  1])

In [ ]:
np.ceil(array) #redondeo 

### FUNCIONES BINARIAS

Son aquellas funciones que reciben como parametrso dos arrays

* add: Adicion de elementos de los dos arrays (equivalente a array1 + array2)
* subtract: Resta de los elementos de los dos arrays (equivalente a array1 - array2)
* multiply: Multiplica los elementos de los dos arrays (equivalente a array1 * array2)
* divide: Divide los elementos de los dos arrays (equivalente a array1 / array2)
* power: Eleva los elementos del primer array a las potencias del segundo (equivalente a array1 ** array2)
* maximum, fmax: Calcula el maximo de los dos arrays (elemento a elemento). fmax ignora NaN
* minimum, fmin:Calcula el minimo de los dos arrays (elemento a elemento). fmin ignora NaN
* mod: Calcula el resto de la division de los dos arrays (equivalente a array1 % array2)
* greater, greater_equal, less, less_qual, equal, not_equal: Comparativas sobre los elementos de ambos ndarrays (elemento a elemento)
* logical_and, logical_or: Operaciones boleanas sobre los elementos de ambos ndarrays (elemento a elemento)

In [ ]:
array1 = np.random.rand(5, 5)
array1

array([[0.02181578, 0.18263442, 0.99915584, 0.3059701 , 0.38437998],
       [0.07275482, 0.85045648, 0.6851169 , 0.99129131, 0.27458217],
       [0.50381128, 0.44390466, 0.1826658 , 0.15648745, 0.29508877],
       [0.68006127, 0.78439069, 0.42498883, 0.27440684, 0.51890503],
       [0.56627011, 0.3562565 , 0.46120204, 0.13183219, 0.69076472]])

In [ ]:
array2 = np.random.rand(5, 5)
array2

array([[0.21641427, 0.31207311, 0.2492018 , 0.19060418, 0.28290199],
       [0.93714804, 0.78360349, 0.92541557, 0.75261037, 0.50843842],
       [0.90264904, 0.27873492, 0.00953631, 0.38077509, 0.42045938],
       [0.19243472, 0.77083105, 0.06019282, 0.8116027 , 0.96118096],
       [0.90172232, 0.05830047, 0.25270937, 0.18151753, 0.06396413]])

In [ ]:
np.minimum(array1, array2) #compara las dos matrices elemento a elemento y arroja el valor minimo de ambas

array([[0.02181578, 0.18263442, 0.2492018 , 0.19060418, 0.28290199],
       [0.07275482, 0.78360349, 0.6851169 , 0.75261037, 0.27458217],
       [0.50381128, 0.27873492, 0.00953631, 0.15648745, 0.29508877],
       [0.19243472, 0.77083105, 0.06019282, 0.27440684, 0.51890503],
       [0.56627011, 0.05830047, 0.25270937, 0.13183219, 0.06396413]])

In [ ]:
np.divide(array1, array2) # divide la matriz1 entre la matriz2 elemento a elemento

array([[ 0.10080565,  0.58522959,  4.00942466,  1.60526436,  1.35870372],
       [ 0.07763429,  1.08531482,  0.7403343 ,  1.31713746,  0.54005   ],
       [ 0.55814747,  1.59256923, 19.15477189,  0.41097082,  0.70182469],
       [ 3.53398426,  1.01759094,  7.06045662,  0.33810489,  0.53986195],
       [ 0.62798725,  6.11069734,  1.82502947,  0.72627803, 10.7992515 ]])

In [ ]:
np.floor_divide(array1, array2)

array([[ 0.,  0.,  4.,  1.,  1.],
       [ 0.,  1.,  0.,  1.,  0.],
       [ 0.,  1., 19.,  0.,  0.],
       [ 3.,  1.,  7.,  0.,  0.],
       [ 0.,  6.,  1.,  0., 10.]])

SELECCION DE ELEMENTOS DE N.D.ARRAYS EN FUNCION DE UNA CONDICION

Numpy pone a nuestra disposicion, a trves de una funcion np.where la poisiblidad de generar un array de salida a partir de dos de entrada, establceiendo una mascara boleana que indiques si (elemento a elemento) debemos enviar a la salida el elementodel primer ndarray (valor true) o de segundo (valor false).

In [ ]:
array1 = np.random.rand(5, 5)
array1

array([[0.37476793, 0.01007352, 0.46268795, 0.88320908, 0.03366352],
       [0.4568405 , 0.76511396, 0.28214077, 0.31723246, 0.83154144],
       [0.42654294, 0.32439823, 0.27109819, 0.56529042, 0.95832378],
       [0.50958776, 0.76599688, 0.85346904, 0.2198772 , 0.80701976],
       [0.83294134, 0.37050333, 0.69015498, 0.82860814, 0.98042696]])

In [ ]:
array2 = np.random.rand(5, 5)
array2

array([[0.57727218, 0.75722466, 0.4295585 , 0.64953667, 0.88053714],
       [0.85105647, 0.50489139, 0.16896275, 0.70272756, 0.11655102],
       [0.55096708, 0.0243341 , 0.69083621, 0.82590086, 0.93554934],
       [0.11650313, 0.1632964 , 0.1485886 , 0.9466145 , 0.46286725],
       [0.08165461, 0.3611877 , 0.14483205, 0.63839847, 0.11717435]])

In [ ]:
# Funsion condicional
np.where(array1 < array2, array1, array2) # funcion, poner la condicion entre ambas matrice, el resulta que debe arroja si se cumple
# y el resulatado que debe arrojar si no se cumple

array([[0.37476793, 0.01007352, 0.4295585 , 0.64953667, 0.03366352],
       [0.4568405 , 0.50489139, 0.16896275, 0.31723246, 0.11655102],
       [0.42654294, 0.0243341 , 0.27109819, 0.56529042, 0.93554934],
       [0.11650313, 0.1632964 , 0.1485886 , 0.2198772 , 0.46286725],
       [0.08165461, 0.3611877 , 0.14483205, 0.63839847, 0.11717435]])

In [ ]:
# Anidacion de Condicion
np.where(array1 < array2, np.where(array1 < 0, 0, array1), array2)

array([[0.37476793, 0.01007352, 0.4295585 , 0.64953667, 0.03366352],
       [0.4568405 , 0.50489139, 0.16896275, 0.31723246, 0.11655102],
       [0.42654294, 0.0243341 , 0.27109819, 0.56529042, 0.93554934],
       [0.11650313, 0.1632964 , 0.1485886 , 0.2198772 , 0.46286725],
       [0.08165461, 0.3611877 , 0.14483205, 0.63839847, 0.11717435]])

### FUNCIONES MATEMATICAS Y ESTADISTICAS


Numpy pone a nuestra disposicion un conjunto de funciones matematicas y estadisticas que se pueden aplicar sobre ndarrays. A continuacion se pueden encontrar los ejemplos mas tipicos ( hay mas que pueden consultarse en la documentaciond e PYTHON)

* sum: suma de elementos
* mean: media aritmetica de los elementos
* median: mediana de los elementos
* std: desviacion estandar
* var: varianza
* min: valor minimo
* max: valor maximo
* argmin: indice de valor minimo (posicion del valor)
* argmax: indice del valor maximo (posicion del valor)
* cumsum: suma acumulada de los elementos
* cumprod: producto acumulado de los elementos




In [ ]:
array_uno = np.random.rand(5, 4)
array_uno

array([[0.76872157, 0.17809585, 0.59414741, 0.8626939 ],
       [0.77705437, 0.27628309, 0.23301521, 0.7984883 ],
       [0.43092978, 0.50011891, 0.01798615, 0.41976605],
       [0.10731882, 0.12435074, 0.44246909, 0.66637328],
       [0.84015958, 0.17008204, 0.0589267 , 0.80125104]])

In [ ]:
# OPERACION GLOBAL
np.sum(array_uno)

9.068231892607368

In [ ]:
# OPERACION POR COLUMNAS
np.sum(array_uno, axis=0) 

array([2.92418414, 1.24893063, 1.34654456, 3.54857257])

In [ ]:
# OPERACION POR FILAS
np.sum(array_uno, axis=1)

array([2.40365873, 2.08484097, 1.36880089, 1.34051193, 1.87041936])

Adicionalmente alguna de estas funciones pueden ser utilizadas como metodos de los ndarrays y no solo como funciones de si mismos.En este caso la sintaxis cambiara y se utlizara la notacion "ndarrays.funtion()"

In [ ]:
array_uno.sum()

9.068231892607368

In [ ]:
np.argmax(array_uno)

3

In [ ]:
np.argmin(array_uno)

In [ ]:
np.cumsum(array_uno)

In [ ]:
np.cumprod(array_uno)

### OPERACIONES SOBRE N.D.ARRAYS BOLEANOS

Dado que internamente, Python intercambia los valores boleanos True como 1 y los falsos como 0, es muy sencillo realizar operaciones matecaticas sobre estos mismos boleanos de forma que se puedan hacer diferentes chequeos_




In [ ]:
array_uno = np.random.rand(5, 5)
array_uno

array([[0.73514033, 0.5022697 , 0.53635459, 0.70462268, 0.9293064 ],
       [0.36183305, 0.7660393 , 0.05416232, 0.67392897, 0.64719695],
       [0.43840864, 0.53009317, 0.86578483, 0.53032153, 0.42403655],
       [0.85983734, 0.53441001, 0.26116817, 0.12155794, 0.82616945],
       [0.02960368, 0.04254352, 0.26262755, 0.40968331, 0.07958586]])

In [ ]:
#ELEMENTOS MAYORES QUE 0
(array_uno > 0). sum() #convierte los elementos TRUE =1 y FALSE =0, despues lo suma

25

In [ ]:
#ELMENTOS MENORES QUE LA MEDIA
(array_uno < array_uno.mean()).sum()

11

Numpy tambien pone a nuestra disposicion dos funciones de chequeo predefinidas sobre ndarrays boleanos
* any: para saber si alguno de los elementos es True
* all: para saber si todos los elementos son True

In [ ]:
#ELEMENTOS MAYORES QUE LA MEDIA
(array_uno == 0). any() #any = hay alguno, o por lo menos uno

In [ ]:
#ELEMENTOS MAYORES QUE LA MEDIA
((array_uno >= -2) & (array_uno <= 2)).all() #all= todos cumplen

### ORDENACION DE N.D.ARRAYS

In [ ]:
array_o = np.random.rand(5, 5)
array_o

In [ ]:
#DATOS ORDENADOS
np.sort(array_o)

In [ ]:
#DATOS ORDENADOS SEGUN EL PRIMER EJE
np.sort(array_o, axis=0)

array([[0.03008455, 0.1001876 , 0.44649657, 0.0720539 , 0.11847888],
       [0.03045116, 0.46031455, 0.45692211, 0.07265647, 0.19249314],
       [0.08973693, 0.67915248, 0.62742801, 0.13819935, 0.27580473],
       [0.25354571, 0.73013829, 0.81099639, 0.40153038, 0.6070831 ],
       [0.2570591 , 0.81387422, 0.96958629, 0.83196836, 0.96589559]])

### FUNCIONES DE CONJUNTO

Numpy permite realizar tratamientos sobre ndarrays asumiendo que le total de los elementos del mismo forman un conjunto
* unique: Calcula el conjunto unico de elementos sin duplicados
* insertsect1d: Calcula la interseccion de los elementos de dos arryas
* union1d: Calcula la union de los elementos de dos arrays 
* in1d : calcula un array boleano que indica si cada elemento del primer array esta contenido en el segundo
* setdifff1d: calcula la diferencia entre ambos conjuntos
* setxord1d: calcula la diferencia simetrica entre ambos conjuntos


In [ ]:
array_1 = np.array([5, 5, 4, 8, 9, 10, 6, 3])
array_1

In [ ]:
array_2 = np.array([8, 2, 4, 8, 7, 15, 6, 1])
array_2

In [ ]:
np.unique(array_1) #eliminar los elementos duplicados de la lista

In [ ]:
np.union1d(array_1, array_2) #juntar las dos listas para crear un conjunto

In [ ]:
np.in1d(array_1, array_2) #comprobar silos elemntos del primer conjunto estan en el segundo